import type {
  Asset,
  PreventiveMaintenance,
  Breakdown,
  SparePart,
  UtilityLog,
  User,
  DashboardStats,
  KPIMetrics,
} from '@/types';

// Mock Users
export const mockUsers: User[] = [
  { id: '1', email: 'admin@factory.com', name: 'Admin User', role: 'admin', createdAt: '2024-01-01' },
  { id: '2', email: 'manager@factory.com', name: 'John Manager', role: 'manager', createdAt: '2024-01-15' },
  { id: '3', email: 'engineer@factory.com', name: 'Sarah Engineer', role: 'engineer', createdAt: '2024-02-01' },
  { id: '4', email: 'operator@factory.com', name: 'Mike Operator', role: 'operator', createdAt: '2024-02-15' },
];

// Mock Assets
export const mockAssets: Asset[] = [
  {
    id: '1',
    assetCode: 'CNC-001',
    assetName: 'CNC Milling Machine',
    assetType: 'machine',
    status: 'active',
    location: 'Shop Floor A',
    manufacturer: 'Mazak',
    serialNumber: 'MZK-2024-001',
    installDate: '2023-06-15',
    lastMaintenance: '2024-12-01',
  },
  {
    id: '2',
    assetCode: 'PRE-002',
    assetName: 'Hydraulic Press 50T',
    assetType: 'machine',
    status: 'active',
    location: 'Shop Floor B',
    manufacturer: 'Schuler',
    serialNumber: 'SCH-2023-045',
    installDate: '2022-03-20',
    lastMaintenance: '2024-11-15',
  },
  {
    id: '3',
    assetCode: 'WLD-003',
    assetName: 'Robot Welding Station',
    assetType: 'equipment',
    status: 'maintenance',
    location: 'Welding Bay',
    manufacturer: 'Fanuc',
    serialNumber: 'FNC-2024-012',
    installDate: '2024-01-10',
  },
  {
    id: '4',
    assetCode: 'CMP-004',
    assetName: 'Air Compressor 100HP',
    assetType: 'auxiliary',
    status: 'active',
    location: 'Utility Room',
    manufacturer: 'Atlas Copco',
    serialNumber: 'ATC-2021-089',
    installDate: '2021-08-05',
    lastMaintenance: '2024-10-20',
  },
  {
    id: '5',
    assetCode: 'LAT-005',
    assetName: 'CNC Lathe',
    assetType: 'machine',
    status: 'inactive',
    location: 'Shop Floor A',
    manufacturer: 'DMG Mori',
    serialNumber: 'DMG-2020-033',
    installDate: '2020-11-12',
  },
];

// Mock PM Schedules
export const mockPMSchedules: PreventiveMaintenance[] = [
  {
    id: '1',
    assetId: '1',
    assetName: 'CNC Milling Machine',
    title: 'Monthly Lubrication',
    description: 'Lubricate all moving parts and check oil levels',
    frequency: 'monthly',
    scheduledDate: '2025-01-20',
    assignedTo: 'Sarah Engineer',
    status: 'scheduled',
    checklist: [
      { id: '1', task: 'Check spindle oil level', completed: false },
      { id: '2', task: 'Lubricate guide rails', completed: false },
      { id: '3', task: 'Inspect coolant level', completed: false },
    ],
  },
  {
    id: '2',
    assetId: '2',
    assetName: 'Hydraulic Press 50T',
    title: 'Weekly Inspection',
    description: 'Check hydraulic pressure and safety systems',
    frequency: 'weekly',
    scheduledDate: '2025-01-17',
    assignedTo: 'Sarah Engineer',
    status: 'overdue',
    checklist: [
      { id: '1', task: 'Check hydraulic fluid level', completed: false },
      { id: '2', task: 'Test emergency stop', completed: false },
      { id: '3', task: 'Inspect hoses for leaks', completed: false },
    ],
  },
  {
    id: '3',
    assetId: '4',
    assetName: 'Air Compressor 100HP',
    title: 'Daily Check',
    description: 'Monitor pressure and drain moisture',
    frequency: 'daily',
    scheduledDate: '2025-01-17',
    assignedTo: 'Mike Operator',
    status: 'in_progress',
    checklist: [
      { id: '1', task: 'Check operating pressure', completed: true },
      { id: '2', task: 'Drain moisture trap', completed: false },
    ],
  },
];

// Mock Breakdowns
export const mockBreakdowns: Breakdown[] = [
  {
    id: '1',
    assetId: '3',
    assetName: 'Robot Welding Station',
    entryDate: '2025-01-15',
    entryTime: '08:30',
    businessUnit: 'Welding',
    operatorId: '4',
    operatorName: 'Mike Operator',
    issue: 'Robot arm not responding to commands',
    status: 'in_progress',
    priority: 'critical',
    engineerNotes: 'Investigating servo motor issue',
  },
  {
    id: '2',
    assetId: '1',
    assetName: 'CNC Milling Machine',
    entryDate: '2025-01-14',
    entryTime: '14:15',
    businessUnit: 'Machining',
    operatorId: '4',
    operatorName: 'Mike Operator',
    issue: 'Unusual vibration during operation',
    status: 'resolved',
    priority: 'medium',
    engineerNotes: 'Spindle bearing replaced',
    resolvedDate: '2025-01-15',
    rootCause: 'Worn spindle bearing',
    actionTaken: 'Replaced spindle bearing and recalibrated',
    downtime: 180,
  },
  {
    id: '3',
    assetId: '2',
    assetName: 'Hydraulic Press 50T',
    entryDate: '2025-01-16',
    entryTime: '10:00',
    businessUnit: 'Press Shop',
    operatorId: '4',
    operatorName: 'Mike Operator',
    issue: 'Minor oil leak detected',
    status: 'open',
    priority: 'low',
  },
];

// Mock Spare Parts
export const mockSpares: SparePart[] = [
  {
    id: '1',
    partCode: 'BRG-6205',
    partName: 'Ball Bearing 6205',
    category: 'Bearings',
    currentStock: 25,
    minStock: 10,
    maxStock: 50,
    unit: 'pcs',
    location: 'Rack A-1',
    unitPrice: 45.00,
    lastRestocked: '2025-01-10',
  },
  {
    id: '2',
    partCode: 'FLT-HYD-01',
    partName: 'Hydraulic Filter Element',
    category: 'Filters',
    currentStock: 5,
    minStock: 8,
    maxStock: 20,
    unit: 'pcs',
    location: 'Rack B-3',
    unitPrice: 120.00,
  },
  {
    id: '3',
    partCode: 'OIL-HYD-46',
    partName: 'Hydraulic Oil ISO 46',
    category: 'Lubricants',
    currentStock: 200,
    minStock: 50,
    maxStock: 500,
    unit: 'L',
    location: 'Tank Area',
    unitPrice: 8.50,
    lastRestocked: '2025-01-05',
  },
  {
    id: '4',
    partCode: 'BLT-V-A68',
    partName: 'V-Belt A68',
    category: 'Belts',
    currentStock: 3,
    minStock: 5,
    maxStock: 15,
    unit: 'pcs',
    location: 'Rack C-2',
    unitPrice: 35.00,
  },
  {
    id: '5',
    partCode: 'SRV-MTR-01',
    partName: 'Servo Motor 2.5kW',
    category: 'Motors',
    currentStock: 1,
    minStock: 2,
    maxStock: 4,
    unit: 'pcs',
    location: 'Electrical Store',
    unitPrice: 2500.00,
  },
];

// Mock Utility Logs
export const mockUtilityLogs: UtilityLog[] = [
  {
    id: '1',
    utilityType: 'power',
    readingValue: 4520,
    unit: 'kWh',
    samplePoint: 'Main Panel',
    recordedAt: '2025-01-17T08:00:00',
    recordedBy: 'System',
  },
  {
    id: '2',
    utilityType: 'gas',
    readingValue: 125,
    unit: 'm³',
    samplePoint: 'Gas Meter 1',
    recordedAt: '2025-01-17T08:00:00',
    recordedBy: 'System',
  },
  {
    id: '3',
    utilityType: 'water',
    readingValue: 850,
    unit: 'm³',
    samplePoint: 'Water Main',
    recordedAt: '2025-01-17T08:00:00',
    recordedBy: 'System',
  },
  {
    id: '4',
    utilityType: 'compressed_air',
    readingValue: 6.5,
    unit: 'bar',
    samplePoint: 'Compressor Output',
    recordedAt: '2025-01-17T08:00:00',
    recordedBy: 'System',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalAssets: 245,
  activeAssets: 198,
  pendingPM: 18,
  overduePM: 5,
  openBreakdowns: 3,
  criticalBreakdowns: 2,
  lowStockItems: 4,
  totalSpares: 1250,
  activeMeters: 87,
  kpiAlerts: 14,
};

// Mock KPI Metrics
export const mockKPIMetrics: KPIMetrics = {
  mttr: 2.5,
  mtbf: 168,
  uptime: 94.5,
  oee: 85.2,
  plannedDowntime: 12,
  unplannedDowntime: 8,
};

// Role permissions
export const rolePermissions = {
  operator: [
    'view_dashboard',
    'view_assets',
    'create_breakdown',
    'view_breakdowns',
    'view_pm',
  ],
  engineer: [
    'view_dashboard',
    'view_assets',
    'create_breakdown',
    'view_breakdowns',
    'update_breakdown',
    'view_pm',
    'update_pm',
    'view_spares',
    'issue_spares',
  ],
  manager: [
    'view_dashboard',
    'view_assets',
    'create_assets',
    'update_assets',
    'view_breakdowns',
    'view_pm',
    'create_pm',
    'update_pm',
    'view_spares',
    'view_utilities',
    'view_kpi',
    'view_analytics',
    'view_reports',
  ],
  admin: [
    'view_dashboard',
    'view_assets',
    'create_assets',
    'update_assets',
    'delete_assets',
    'view_breakdowns',
    'update_breakdown',
    'delete_breakdown',
    'view_pm',
    'create_pm',
    'update_pm',
    'delete_pm',
    'view_spares',
    'create_spares',
    'update_spares',
    'delete_spares',
    'issue_spares',
    'view_utilities',
    'create_utilities',
    'view_kpi',
    'view_analytics',
    'view_reports',
    'manage_users',
    'manage_roles',
  ],
};
